version: '3'
services:
  crawler-book-douban:
    container_name: 'crawler-book-douban'
    restart: always
    build: .
    image: 'germey/crawler-book-douban'
    command: 'python3 run.py'
    environment:
      REDIS_CONNECTION_STRING:
      PROXYPOOL_URL:
      PROXYTUNNEL_URL:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD: